version: '2'
services:
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: directual
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: directual

  zk:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka    
    depends_on:
      - zk
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      # HOSTNAME_COMMAND: route -n | awk '/UG[ \t]/{print $$2}'
      HOSTNAME_COMMAND: ip addr show eth0 | grep inet | awk '{print $$2}' | awk -F "/" '{print $$1}'

  redis:
    image: redis:3.2

  # elastic:
    # image: elasticsearch:5.5