version: '3'
services:
  
  # selenoid:
    # network_mode: bridge
    # image: aerokube/selenoid:latest-release
    # volumes:
      # - "$PWD:/etc/selenoid"
      # - "/var/run/docker.sock:/var/run/docker.sock"
    # ports:
      # - "4444:4444"


  postgres:
    network_mode: bridge
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: directual
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: directual

  # postgresdata:
  #   image: postgres:9.5
  #   ports:
  #     - "5430:5432"
  #   environment:
  #     POSTGRES_USER: directual
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: directual    

  # kafka_zk:
    # image: johnnypark/kafka-zookeeper
    # ports:
    #   - "2181:2181"
    #   - "9092:9092"
    # environment:
    #   #ADVERTISED_HOST: 127.0.0.1
    #   ADVERTISED_HOST: 172.22.0.7

  zk:
    network_mode: bridge
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    network_mode: bridge
    image: wurstmeister/kafka    
    depends_on:
      - zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      HOSTNAME_COMMAND: route -n | awk '/UG[ \t]/{print $$2}'

  # kafka_zk:
  #   image: spotify/kafka
  #   ports:
  #     - "2181:2181"
  #     - "9092:9092"
  #   environment:
  #     ADVERTISED_PORT: 9092
  #     # ADVERTISED_HOST: kafka_zk
  #     ADVERTISED_HOST: "${docker-machine ip}"

  mongodb:
    network_mode: bridge
    image: mongo
    ports:
      - "27017:27017"

  redis:
    network_mode: bridge
    image: redis:3.2
    ports:
      - "6379:6379"


  web_ui:
    network_mode: bridge
    image: gitlab.directual.com:5005/platform/directual-server/${WEB_UI_IMAGE}
    depends_on:
      - kafka
      - zk
      - postgres
      - redis
    ports:
      - "8080:8080"
      - "8099:8099"
    environment:
      HOST_HOSTNAME: web_ui_test
      JAVA_OPTS: 
      GRAPHITE_HOST:
      GRAPHITE_PORT:
      GRAPHITE_API_URL:
      DIRECTUAL_LOCK-SERIVCE_REDIS_HOST: redis
      DIRECTUAL_LOCK-SERIVCE_REDIS_PORT: 6379
      SERVICE_REDIS_HOSTS: redis:6379
      DIRECTUAL_LOCK-SERVICE_REDIS_HOSTS: redis:6379
      DIRECTUAL_INDEXER_ELASTIC_HOSTS: elastic:9300
      DIRECTUAL_SCENARIODATASOURCECLASS: ${DATASOURCE}
      DIRECTUAL.SCENARIODATASOURCECLASSPARAMS: ${DATASOURCE_PARAMS}
      # HBASE_ZOOKEEPER: 172.22.0.7
      HBASE_ZOOKEEPER: zk
      # TELEGRAM_ENABLE: False
      DATABASE_URL: jdbc:postgresql://postgres/directual
      DATABASE_USER: directual
      DATABASE_PASSWORD: 123456
      # DIRECTUAL_CONFIG_PATH: /usr/local/tomcat/conf/directual.conf
      # KAFKA_HOST: 172.22.0.7:9092
      # KAFKA_HOST: kafka_zk:9092
      KAFKA_HOST: kafka:9092
      # ZOOKEEPER_QUORUM: 172.22.0.7:2181
      ZOOKEEPER_QUORUM: zk:2181
      DERECTUAL_UI_TYPE: PORTAL
      DIRECTUAL_UPLOADPATH: /tmp
      DIRECTUAL_APPLICATIONKEYS_DEFAULTAPPID: ${TEST_APP_ID}
      DIRECTUAL_APPLICATIONKEYS_DEFAULTSECRET: ${TEST_APP_SECRET}

      

      

  
  elastic:
    network_mode: bridge
    image: elasticsearch:5.5
    ports:
      - "9300:9300"

