version: '2'
services:
  selenoid:
    image: "aerokube/selenoid"
    command: -container-network ${COMPOSE_PROJECT_NAME}_default -enable-file-upload -timeout 5m
    volumes:
      - "$PWD/selenoid:/etc/selenoid/" 
      - "/var/run/docker.sock:/var/run/docker.sock"
