version: '3'
services:
  
#  selenoid:
#   # network_mode: bridge
#    image: aerokube/selenoid:latest-release
#    volumes:
#      - "$PWD/selenoid:/etc/selenoid"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "${HOME}:/root"
#    ports:
#      - "4444:4444"
#    environment:
#      OVERRIDE_HOME: ${HOME}
#    # command: selenoid start --vnc --tmpfs 128 -g "--container-network testcases_default"
#    command: selenoid start --vnc --tmpfs 128 -g "--container-network qa-core"


  postgres:
#    network_mode: bridge
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: directual
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: directual

  # postgresdata:
  #   image: postgres:9.5
  #   ports:
  #     - "5430:5432"
  #   environment:
  #     POSTGRES_USER: directual
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: directual    

  # kafka_zk:
    # image: johnnypark/kafka-zookeeper
    # ports:
    #   - "2181:2181"
    #   - "9092:9092"
    # environment:
    #   #ADVERTISED_HOST: 127.0.0.1
    #   ADVERTISED_HOST: 172.22.0.7

  zk:
#    network_mode: bridge
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
#    network_mode: bridge
    image: wurstmeister/kafka    
    depends_on:
      - zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      HOSTNAME_COMMAND: route -n | awk '/UG[ \t]/{print $$2}'

  # kafka_zk:
  #   image: spotify/kafka
  #   ports:
  #     - "2181:2181"
  #     - "9092:9092"
  #   environment:
  #     ADVERTISED_PORT: 9092
  #     # ADVERTISED_HOST: kafka_zk
  #     ADVERTISED_HOST: "${docker-machine ip}"

  
  redis:
#    network_mode: bridge
    image: redis:3.2
    ports:
      - "6379:6379"



      

  
  elastic:
#    network_mode: bridge
    image: elasticsearch:5.5
    ports:
      - "9300:9300"

