# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import CommonRequestResponse_pb2 as CommonRequestResponse__pb2
import DTO_pb2 as DTO__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


class DatasourceRemoteServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/DatasourceRemoteService/Ping',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateIndeces = channel.unary_unary(
        '/DatasourceRemoteService/UpdateIndeces',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithFieldsRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Truncate = channel.unary_unary(
        '/DatasourceRemoteService/Truncate',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.RemoveFieldsData = channel.unary_unary(
        '/DatasourceRemoteService/RemoveFieldsData',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithFieldsRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.NativeVersionSupport = channel.unary_unary(
        '/DatasourceRemoteService/NativeVersionSupport',
        request_serializer=CommonRequestResponse__pb2.NetworkIDRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.Save = channel.unary_unary(
        '/DatasourceRemoteService/Save',
        request_serializer=CommonRequestResponse__pb2.ScenarioObjectDTOWrapperWithStructInfo.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectDTOWrapper.FromString,
        )
    self.SaveBatch = channel.unary_unary(
        '/DatasourceRemoteService/SaveBatch',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithScenarioObjectListRequestWithStructInfo.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectListDTO.FromString,
        )
    self.FindBySID = channel.unary_unary(
        '/DatasourceRemoteService/FindBySID',
        request_serializer=CommonRequestResponse__pb2.BasicScenarioObjDTOWithStructInfo.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectOptionDTO.FromString,
        )
    self.FindByOID = channel.unary_unary(
        '/DatasourceRemoteService/FindByOID',
        request_serializer=CommonRequestResponse__pb2.BasicScenarioObjDTOWithStructInfo.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectOptionDTO.FromString,
        )
    self.FindByOIDWithFields = channel.unary_unary(
        '/DatasourceRemoteService/FindByOIDWithFields',
        request_serializer=CommonRequestResponse__pb2.BasicScenarioObjWithFieldsRequest.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectOptionDTO.FromString,
        )
    self.SimpleFindByOID = channel.unary_unary(
        '/DatasourceRemoteService/SimpleFindByOID',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithObjectIDWithFieldsRequest.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectOptionDTO.FromString,
        )
    self.Fields = channel.unary_unary(
        '/DatasourceRemoteService/Fields',
        request_serializer=CommonRequestResponse__pb2.BasicScenarioObjWithFieldsRequest.SerializeToString,
        response_deserializer=DTO__pb2.FieldsValues.FromString,
        )
    self.FieldsPartial = channel.unary_unary(
        '/DatasourceRemoteService/FieldsPartial',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithObjectIDWithFieldsRequest.SerializeToString,
        response_deserializer=DTO__pb2.FieldsValues.FromString,
        )
    self.Versions = channel.unary_unary(
        '/DatasourceRemoteService/Versions',
        request_serializer=CommonRequestResponse__pb2.VersionsRequest.SerializeToString,
        response_deserializer=DTO__pb2.VersionInformationListDTO.FromString,
        )
    self.SystemFieldVersions = channel.unary_unary(
        '/DatasourceRemoteService/SystemFieldVersions',
        request_serializer=CommonRequestResponse__pb2.BasicScenarioObjWithMaxVersionWithFieldRequest.SerializeToString,
        response_deserializer=DTO__pb2.VersionInformationListDTO.FromString,
        )
    self.Exist = channel.unary_unary(
        '/DatasourceRemoteService/Exist',
        request_serializer=DTO__pb2.BasicScenarioObjDTO.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.Report = channel.unary_unary(
        '/DatasourceRemoteService/Report',
        request_serializer=CommonRequestResponse__pb2.BuildReportRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Remove = channel.unary_unary(
        '/DatasourceRemoteService/Remove',
        request_serializer=DTO__pb2.BasicScenarioObjDTO.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.List = channel.unary_unary(
        '/DatasourceRemoteService/List',
        request_serializer=CommonRequestResponse__pb2.StructListRequest.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectPagedDTO.FromString,
        )
    self.TableSize = channel.unary_unary(
        '/DatasourceRemoteService/TableSize',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.FromString,
        )
    self.LastObjects = channel.unary_unary(
        '/DatasourceRemoteService/LastObjects',
        request_serializer=CommonRequestResponse__pb2.NetworkIDRequest.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectListDTO.FromString,
        )
    self.ChangeFieldObject = channel.unary_unary(
        '/DatasourceRemoteService/ChangeFieldObject',
        request_serializer=CommonRequestResponse__pb2.FieldsWithDataRequest.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectOptionDTO.FromString,
        )
    self.NativeIndexSupport = channel.unary_unary(
        '/DatasourceRemoteService/NativeIndexSupport',
        request_serializer=CommonRequestResponse__pb2.NetworkIDRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.NativeAggregationSupport = channel.unary_unary(
        '/DatasourceRemoteService/NativeAggregationSupport',
        request_serializer=CommonRequestResponse__pb2.NetworkIDRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.Healthcheck = channel.unary_unary(
        '/DatasourceRemoteService/Healthcheck',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.Exists = channel.unary_unary(
        '/DatasourceRemoteService/Exists',
        request_serializer=CommonRequestResponse__pb2.ExistsRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
        )
    self.FindObjectByFilter = channel.unary_unary(
        '/DatasourceRemoteService/FindObjectByFilter',
        request_serializer=CommonRequestResponse__pb2.FindObjectRequest.SerializeToString,
        response_deserializer=DTO__pb2.ScenarioObjectPagedDTO.FromString,
        )
    self.ProcessObjects = channel.unary_stream(
        '/DatasourceRemoteService/ProcessObjects',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.SerializeToString,
        response_deserializer=DTO__pb2.ObjectInfoDTO.FromString,
        )
    self.ProcessObjectsWithFields = channel.unary_stream(
        '/DatasourceRemoteService/ProcessObjectsWithFields',
        request_serializer=CommonRequestResponse__pb2.ProcessObjectRequest.SerializeToString,
        response_deserializer=DTO__pb2.ObjectWithFieldsDTO.FromString,
        )
    self.BatchFields = channel.unary_stream(
        '/DatasourceRemoteService/BatchFields',
        request_serializer=CommonRequestResponse__pb2.BatchFieldsRequest.SerializeToString,
        response_deserializer=DTO__pb2.ObjectWithFieldsDTO.FromString,
        )
    self.SimpleAggregate = channel.unary_unary(
        '/DatasourceRemoteService/SimpleAggregate',
        request_serializer=CommonRequestResponse__pb2.SimpleAggregateRequest.SerializeToString,
        response_deserializer=DTO__pb2.FieldDataValue.FromString,
        )


class DatasourceRemoteServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateIndeces(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Truncate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveFieldsData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NativeVersionSupport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Save(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveBatch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindBySID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByOID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByOIDWithFields(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimpleFindByOID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Fields(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FieldsPartial(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Versions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SystemFieldVersions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Exist(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Report(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Remove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TableSize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LastObjects(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ChangeFieldObject(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NativeIndexSupport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NativeAggregationSupport(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Healthcheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Exists(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindObjectByFilter(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessObjects(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ProcessObjectsWithFields(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BatchFields(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SimpleAggregate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatasourceRemoteServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateIndeces': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateIndeces,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithFieldsRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Truncate': grpc.unary_unary_rpc_method_handler(
          servicer.Truncate,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'RemoveFieldsData': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveFieldsData,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithFieldsRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'NativeVersionSupport': grpc.unary_unary_rpc_method_handler(
          servicer.NativeVersionSupport,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'Save': grpc.unary_unary_rpc_method_handler(
          servicer.Save,
          request_deserializer=CommonRequestResponse__pb2.ScenarioObjectDTOWrapperWithStructInfo.FromString,
          response_serializer=DTO__pb2.ScenarioObjectDTOWrapper.SerializeToString,
      ),
      'SaveBatch': grpc.unary_unary_rpc_method_handler(
          servicer.SaveBatch,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithScenarioObjectListRequestWithStructInfo.FromString,
          response_serializer=DTO__pb2.ScenarioObjectListDTO.SerializeToString,
      ),
      'FindBySID': grpc.unary_unary_rpc_method_handler(
          servicer.FindBySID,
          request_deserializer=CommonRequestResponse__pb2.BasicScenarioObjDTOWithStructInfo.FromString,
          response_serializer=DTO__pb2.ScenarioObjectOptionDTO.SerializeToString,
      ),
      'FindByOID': grpc.unary_unary_rpc_method_handler(
          servicer.FindByOID,
          request_deserializer=CommonRequestResponse__pb2.BasicScenarioObjDTOWithStructInfo.FromString,
          response_serializer=DTO__pb2.ScenarioObjectOptionDTO.SerializeToString,
      ),
      'FindByOIDWithFields': grpc.unary_unary_rpc_method_handler(
          servicer.FindByOIDWithFields,
          request_deserializer=CommonRequestResponse__pb2.BasicScenarioObjWithFieldsRequest.FromString,
          response_serializer=DTO__pb2.ScenarioObjectOptionDTO.SerializeToString,
      ),
      'SimpleFindByOID': grpc.unary_unary_rpc_method_handler(
          servicer.SimpleFindByOID,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithObjectIDWithFieldsRequest.FromString,
          response_serializer=DTO__pb2.ScenarioObjectOptionDTO.SerializeToString,
      ),
      'Fields': grpc.unary_unary_rpc_method_handler(
          servicer.Fields,
          request_deserializer=CommonRequestResponse__pb2.BasicScenarioObjWithFieldsRequest.FromString,
          response_serializer=DTO__pb2.FieldsValues.SerializeToString,
      ),
      'FieldsPartial': grpc.unary_unary_rpc_method_handler(
          servicer.FieldsPartial,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDWithObjectIDWithFieldsRequest.FromString,
          response_serializer=DTO__pb2.FieldsValues.SerializeToString,
      ),
      'Versions': grpc.unary_unary_rpc_method_handler(
          servicer.Versions,
          request_deserializer=CommonRequestResponse__pb2.VersionsRequest.FromString,
          response_serializer=DTO__pb2.VersionInformationListDTO.SerializeToString,
      ),
      'SystemFieldVersions': grpc.unary_unary_rpc_method_handler(
          servicer.SystemFieldVersions,
          request_deserializer=CommonRequestResponse__pb2.BasicScenarioObjWithMaxVersionWithFieldRequest.FromString,
          response_serializer=DTO__pb2.VersionInformationListDTO.SerializeToString,
      ),
      'Exist': grpc.unary_unary_rpc_method_handler(
          servicer.Exist,
          request_deserializer=DTO__pb2.BasicScenarioObjDTO.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'Report': grpc.unary_unary_rpc_method_handler(
          servicer.Report,
          request_deserializer=CommonRequestResponse__pb2.BuildReportRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Remove': grpc.unary_unary_rpc_method_handler(
          servicer.Remove,
          request_deserializer=DTO__pb2.BasicScenarioObjDTO.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=CommonRequestResponse__pb2.StructListRequest.FromString,
          response_serializer=DTO__pb2.ScenarioObjectPagedDTO.SerializeToString,
      ),
      'TableSize': grpc.unary_unary_rpc_method_handler(
          servicer.TableSize,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.UInt64Value.SerializeToString,
      ),
      'LastObjects': grpc.unary_unary_rpc_method_handler(
          servicer.LastObjects,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDRequest.FromString,
          response_serializer=DTO__pb2.ScenarioObjectListDTO.SerializeToString,
      ),
      'ChangeFieldObject': grpc.unary_unary_rpc_method_handler(
          servicer.ChangeFieldObject,
          request_deserializer=CommonRequestResponse__pb2.FieldsWithDataRequest.FromString,
          response_serializer=DTO__pb2.ScenarioObjectOptionDTO.SerializeToString,
      ),
      'NativeIndexSupport': grpc.unary_unary_rpc_method_handler(
          servicer.NativeIndexSupport,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'NativeAggregationSupport': grpc.unary_unary_rpc_method_handler(
          servicer.NativeAggregationSupport,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'Healthcheck': grpc.unary_unary_rpc_method_handler(
          servicer.Healthcheck,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'Exists': grpc.unary_unary_rpc_method_handler(
          servicer.Exists,
          request_deserializer=CommonRequestResponse__pb2.ExistsRequest.FromString,
          response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
      ),
      'FindObjectByFilter': grpc.unary_unary_rpc_method_handler(
          servicer.FindObjectByFilter,
          request_deserializer=CommonRequestResponse__pb2.FindObjectRequest.FromString,
          response_serializer=DTO__pb2.ScenarioObjectPagedDTO.SerializeToString,
      ),
      'ProcessObjects': grpc.unary_stream_rpc_method_handler(
          servicer.ProcessObjects,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.FromString,
          response_serializer=DTO__pb2.ObjectInfoDTO.SerializeToString,
      ),
      'ProcessObjectsWithFields': grpc.unary_stream_rpc_method_handler(
          servicer.ProcessObjectsWithFields,
          request_deserializer=CommonRequestResponse__pb2.ProcessObjectRequest.FromString,
          response_serializer=DTO__pb2.ObjectWithFieldsDTO.SerializeToString,
      ),
      'BatchFields': grpc.unary_stream_rpc_method_handler(
          servicer.BatchFields,
          request_deserializer=CommonRequestResponse__pb2.BatchFieldsRequest.FromString,
          response_serializer=DTO__pb2.ObjectWithFieldsDTO.SerializeToString,
      ),
      'SimpleAggregate': grpc.unary_unary_rpc_method_handler(
          servicer.SimpleAggregate,
          request_deserializer=CommonRequestResponse__pb2.SimpleAggregateRequest.FromString,
          response_serializer=DTO__pb2.FieldDataValue.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DatasourceRemoteService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
