# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import CommonRequestResponse_pb2 as CommonRequestResponse__pb2
import DTO_pb2 as DTO__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MetadataRemoteServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/MetadataRemoteService/Ping',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ClearCache = channel.unary_unary(
        '/MetadataRemoteService/ClearCache',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FindByID = channel.unary_unary(
        '/MetadataRemoteService/FindByID',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.SerializeToString,
        response_deserializer=DTO__pb2.StructureOptionDTO.FromString,
        )
    self.FindBySysName = channel.unary_unary(
        '/MetadataRemoteService/FindBySysName',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructSysNameRequest.SerializeToString,
        response_deserializer=DTO__pb2.StructureOptionDTO.FromString,
        )
    self.FindByNetworkID = channel.unary_unary(
        '/MetadataRemoteService/FindByNetworkID',
        request_serializer=CommonRequestResponse__pb2.NetworkIDRequest.SerializeToString,
        response_deserializer=DTO__pb2.StructureListDTO.FromString,
        )
    self.FindWithoutSystemFields = channel.unary_unary(
        '/MetadataRemoteService/FindWithoutSystemFields',
        request_serializer=CommonRequestResponse__pb2.NetworkIDWithStructSysNameRequest.SerializeToString,
        response_deserializer=DTO__pb2.StructureOptionDTO.FromString,
        )
    self.FindAllBySysName = channel.unary_unary(
        '/MetadataRemoteService/FindAllBySysName',
        request_serializer=CommonRequestResponse__pb2.StructSysNameRequest.SerializeToString,
        response_deserializer=DTO__pb2.StructureListDTO.FromString,
        )
    self.ScenarioDirectoriesMapping = channel.unary_unary(
        '/MetadataRemoteService/ScenarioDirectoriesMapping',
        request_serializer=CommonRequestResponse__pb2.NetworkIDRequest.SerializeToString,
        response_deserializer=CommonRequestResponse__pb2.ScenarioDirectoruesDTO.FromString,
        )


class MetadataRemoteServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearCache(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindBySysName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindByNetworkID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindWithoutSystemFields(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindAllBySysName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ScenarioDirectoriesMapping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MetadataRemoteServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ClearCache': grpc.unary_unary_rpc_method_handler(
          servicer.ClearCache,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FindByID': grpc.unary_unary_rpc_method_handler(
          servicer.FindByID,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructIDRequest.FromString,
          response_serializer=DTO__pb2.StructureOptionDTO.SerializeToString,
      ),
      'FindBySysName': grpc.unary_unary_rpc_method_handler(
          servicer.FindBySysName,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructSysNameRequest.FromString,
          response_serializer=DTO__pb2.StructureOptionDTO.SerializeToString,
      ),
      'FindByNetworkID': grpc.unary_unary_rpc_method_handler(
          servicer.FindByNetworkID,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDRequest.FromString,
          response_serializer=DTO__pb2.StructureListDTO.SerializeToString,
      ),
      'FindWithoutSystemFields': grpc.unary_unary_rpc_method_handler(
          servicer.FindWithoutSystemFields,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDWithStructSysNameRequest.FromString,
          response_serializer=DTO__pb2.StructureOptionDTO.SerializeToString,
      ),
      'FindAllBySysName': grpc.unary_unary_rpc_method_handler(
          servicer.FindAllBySysName,
          request_deserializer=CommonRequestResponse__pb2.StructSysNameRequest.FromString,
          response_serializer=DTO__pb2.StructureListDTO.SerializeToString,
      ),
      'ScenarioDirectoriesMapping': grpc.unary_unary_rpc_method_handler(
          servicer.ScenarioDirectoriesMapping,
          request_deserializer=CommonRequestResponse__pb2.NetworkIDRequest.FromString,
          response_serializer=CommonRequestResponse__pb2.ScenarioDirectoruesDTO.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MetadataRemoteService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
