# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MetadataRemoteService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DTO_pb2 as DTO__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import CommonRequestResponse_pb2 as CommonRequestResponse__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MetadataRemoteService.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1bMetadataRemoteService.proto\x1a\tDTO.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1b\x43ommonRequestResponse.proto2\xc3\x04\n\x15MetadataRemoteService\x12\x38\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12\x45\n\nClearCache\x12\x1d.NetworkIDWithStructIDRequest\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x08\x46indByID\x12\x1d.NetworkIDWithStructIDRequest\x1a\x13.StructureOptionDTO\"\x00\x12J\n\rFindBySysName\x12\".NetworkIDWithStructSysNameRequest\x1a\x13.StructureOptionDTO\"\x00\x12\x39\n\x0f\x46indByNetworkID\x12\x11.NetworkIDRequest\x1a\x11.StructureListDTO\"\x00\x12T\n\x17\x46indWithoutSystemFields\x12\".NetworkIDWithStructSysNameRequest\x1a\x13.StructureOptionDTO\"\x00\x12>\n\x10\x46indAllBySysName\x12\x15.StructSysNameRequest\x1a\x11.StructureListDTO\"\x00\x12J\n\x1aScenarioDirectoriesMapping\x12\x11.NetworkIDRequest\x1a\x17.ScenarioDirectoruesDTO\"\x00\x42\x33\n com.directual.generated.servicesB\rMetadataProtoP\x01\x62\x06proto3')
  ,
  dependencies=[DTO__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,CommonRequestResponse__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n com.directual.generated.servicesB\rMetadataProtoP\001'))

_METADATAREMOTESERVICE = _descriptor.ServiceDescriptor(
  name='MetadataRemoteService',
  full_name='MetadataRemoteService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=101,
  serialized_end=680,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='MetadataRemoteService.Ping',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ClearCache',
    full_name='MetadataRemoteService.ClearCache',
    index=1,
    containing_service=None,
    input_type=CommonRequestResponse__pb2._NETWORKIDWITHSTRUCTIDREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindByID',
    full_name='MetadataRemoteService.FindByID',
    index=2,
    containing_service=None,
    input_type=CommonRequestResponse__pb2._NETWORKIDWITHSTRUCTIDREQUEST,
    output_type=DTO__pb2._STRUCTUREOPTIONDTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindBySysName',
    full_name='MetadataRemoteService.FindBySysName',
    index=3,
    containing_service=None,
    input_type=CommonRequestResponse__pb2._NETWORKIDWITHSTRUCTSYSNAMEREQUEST,
    output_type=DTO__pb2._STRUCTUREOPTIONDTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindByNetworkID',
    full_name='MetadataRemoteService.FindByNetworkID',
    index=4,
    containing_service=None,
    input_type=CommonRequestResponse__pb2._NETWORKIDREQUEST,
    output_type=DTO__pb2._STRUCTURELISTDTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindWithoutSystemFields',
    full_name='MetadataRemoteService.FindWithoutSystemFields',
    index=5,
    containing_service=None,
    input_type=CommonRequestResponse__pb2._NETWORKIDWITHSTRUCTSYSNAMEREQUEST,
    output_type=DTO__pb2._STRUCTUREOPTIONDTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindAllBySysName',
    full_name='MetadataRemoteService.FindAllBySysName',
    index=6,
    containing_service=None,
    input_type=CommonRequestResponse__pb2._STRUCTSYSNAMEREQUEST,
    output_type=DTO__pb2._STRUCTURELISTDTO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ScenarioDirectoriesMapping',
    full_name='MetadataRemoteService.ScenarioDirectoriesMapping',
    index=7,
    containing_service=None,
    input_type=CommonRequestResponse__pb2._NETWORKIDREQUEST,
    output_type=CommonRequestResponse__pb2._SCENARIODIRECTORUESDTO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METADATAREMOTESERVICE)

DESCRIPTOR.services_by_name['MetadataRemoteService'] = _METADATAREMOTESERVICE

# @@protoc_insertion_point(module_scope)
